### ISSUE TITLE
User Auth MVP

### ISSUE THREAD

**Issue by ken8waru1** [ken8waru1/slide#2]
Hey, Andy, I've finished user auth functionality. 

### Functionality:
Works great! Your signup and login routes cannot be navigated to when logged in, and demo account works well.

### Styling
- [x] Please model your splash page - "/" - to mimic Slack's home page www.slack.com:
   - [x] Add a welcome h1 or text
   - [x] Add button/link to "try it free" that links to the signup page
- [x] Adjust your navbar to include 2 x sub-divs - leftbar & rightbar. Set these to display: flex, and give left and right padding of 10%:
   - [x] leftbar should contain your logo
   - [x] rightbar should contain your Login and Get Started elements

This should give your navbar are more evenly centered appearance

**Comment by minucos** [comment]
Hi Ken

I have edited the issue to add my notes on any changes I think you should make. Just some styling corrections mainly to center your navbar elements.

I have also added a note for you to add some more styling to your landing page in order to more mimic Slack's styling. No need to copy the entire marketing speech, just a big h1 and maybe an input or button.

Take a look through and let me know when you are finished.

If you need any clarification just let me know, and nice work on the animations!

Andy

**Comment by ken8waru1** [comment]
Hey, Andy, I pushed the changes with my updated navbar and splash page to Heroku if you could take a look when you can.
